# 基本項目
apiVersion: v1
kind: Service
metadata:
  name: food-recognition

# Serviceのスペック
spec:
  #type: LoadBalancer
  ports:   # ポート番号
    - port: 80
      targetPort: 80
      protocol: TCP
  
  # C. Podの条件(ラベル)
  selector:
    app: food
