# 基本項目
apiVersion: v1
kind: Service
metadata:
  name: web-front

# Serviceのスペック
spec:
  type: LoadBalancer
  ports:   # ポート番号
    - port: 80
      targetPort: 3000
      protocol: TCP

  # Podの条件(ラベル)
  selector:
    app: front
